FORWARD = "FORWARD"
BACKWARD = "BACKWARD"

HORIZONTAL = "HORIZONTAL"
VERTICAL = "VERTICAL"

MAT_HORIZONTAL = "MAT_HORIZONTAL"
MAT_VERTICAL = "MAT_VERTICAL"
WIRE_HORIZONTAL = "WIRE_HORIZONTAL"
WIRE_VERTICAL = "WIRE_VERTICAL"

MAX_SOCKET_DISTANCE = 370
MAX_WIRE_LENGTH = 150000
MAX_MATS_PER_ROOM = 100

FX_FY = (1, 1)
BX_FY = (-1, 1)
BX_BY = (-1, -1)
FX_BY = (1, -1)
